export { default as About } from "./About"
export { default as Awards } from "./Awards"
export { default as Footer } from "./Footer"
export { default as Hero } from "./Hero"
export { default as Navbar } from "./Navbar"
export { default as Services } from "./Services"
export { default as Shots } from "./Shots"
export { default as Work } from "./Work"